name: Asp Net deploy azure

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 12teyrtgf
          MONGO_INITDB_DATABASE: tododb
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0
      - run: |
          dotnet restore
          cd .. && cd MinimalAPIDemo.Test && dotnet restore
          dotnet test MinimalAPIDemo.Test

  build:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Azure Contaiern Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/${{ secrets.REGISTRY_USERNAME }}:latest

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: deploying to aks
  #       uses:
